# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.version.version)


2.1.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [13]:
a = np.random.default_rng().random((2, 3, 5))

y = np.random.rand(2, 3, 5)

z = np.random.randn(2, 3, 5)

print(a, y, z)

[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]] [[[0.22150081 0.1594968  0.38633369 0.077987   0.47166029]
  [0.11486504 0.79158677 0.58079163 0.99093359 0.42240909]
  [0.99184066 0.66702126 0.91039658 0.638456   0.25166603]]

 [[0.65988459 0.39170919 0.52460622 0.61687532 0.29947415]
  [0.65046541 0.54864503 0.5010481  0.71689438 0.58254612]
  [0.55117922 0.34153362 0.18128507 0.98011885 0.20377934]]] [[[ 0.03675562  0.39707746 -0.3307082   1.48733153 -0.10348089]
  [ 0.81312758  0.13634459 -2.18847786  0.41292972 -0.15742026]
  [ 1.0152189   1.77753958 -0.67949084 -1.56765378 -1.29011227]]

 [[-0.11151084  0.2437583   1.63616589  0.07316999  1.13219504]
  [-0.1973946  -0.70492147


### 4. Print a.


In [14]:
print(a)

[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [15]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [18]:
np.size(a) == np.size(b)
# The two arrays have the same size, meaning they have the same number of elements.

True


### 8. Are you able to add a and b? Why or why not?


In [19]:
# a and b don't have the same shape even if they have the same number of elements we can't add them.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [20]:
c = np.reshape(b, (2, 3, 5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [23]:
d = a + c
print(d)
# It works because a and c have the same shape.

[[[1.50709764 1.77978579 1.70699607 1.70438251 1.7104036 ]
  [1.8828242  1.45090692 1.83865915 1.00854134 1.94583259]
  [1.85778214 1.53702586 1.83717413 1.57513617 1.6714281 ]]

 [[1.76332445 1.6711872  1.12508889 1.65463712 1.29220718]
  [1.86298343 1.91415652 1.93438023 1.25507195 1.24665208]
  [1.50237124 1.43527208 1.00622265 1.15474279 1.48375149]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [25]:
print(a)
print(d)
# The values of a and d are different because d is the result of adding a and c, where c is an array of ones. Each element in d is equal to the corresponding element in a plus 1.

[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]]
[[[1.50709764 1.77978579 1.70699607 1.70438251 1.7104036 ]
  [1.8828242  1.45090692 1.83865915 1.00854134 1.94583259]
  [1.85778214 1.53702586 1.83717413 1.57513617 1.6714281 ]]

 [[1.76332445 1.6711872  1.12508889 1.65463712 1.29220718]
  [1.86298343 1.91415652 1.93438023 1.25507195 1.24665208]
  [1.50237124 1.43527208 1.00622265 1.15474279 1.48375149]]]



### 12. Multiply a and c. Assign the result to e.


In [27]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [29]:
print(a)
print(e)
# The values of a and e are the same because e is the result of multiplying a and c, where c is an array of ones. Each element in e is equal to the corresponding element in a.

[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]]
[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [40]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_mean, d_min)

1.9458325911424974 1.5772008504477002 1.0062226468363797



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [32]:
f = np.empty((2, 3, 5))
print(f)

[[[0.50709764 0.77978579 0.70699607 0.70438251 0.7104036 ]
  [0.8828242  0.45090692 0.83865915 0.00854134 0.94583259]
  [0.85778214 0.53702586 0.83717413 0.57513617 0.6714281 ]]

 [[0.76332445 0.6711872  0.12508889 0.65463712 0.29220718]
  [0.86298343 0.91415652 0.93438023 0.25507195 0.24665208]
  [0.50237124 0.43527208 0.00622265 0.15474279 0.48375149]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [38]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [39]:
print(d)
print(f)

[[[1.50709764 1.77978579 1.70699607 1.70438251 1.7104036 ]
  [1.8828242  1.45090692 1.83865915 1.00854134 1.94583259]
  [1.85778214 1.53702586 1.83717413 1.57513617 1.6714281 ]]

 [[1.76332445 1.6711872  1.12508889 1.65463712 1.29220718]
  [1.86298343 1.91415652 1.93438023 1.25507195 1.24665208]
  [1.50237124 1.43527208 1.00622265 1.15474279 1.48375149]]]
[[[ 25.  75.  75.  75.  75.]
  [ 75.  25.  75.  25. 100.]
  [ 75.  25.  75.  25.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  25.   0.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]